sudo: false
language: elixir
elixir:
  - 1.3.3
otp_release:
  - 18.2
  - 19.0
env:
  - MIX_ENV=test
install:
  - rm -rf _build
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
notifications:
  email:
    - dneighman@gmail.com
addons:
  postgresql: "9.4"
services:
  - postgresql

before_script:
  - psql -c 'create database phoenix_guardian_test;' -U postgres
